version: "3.3"

services:
  cursoheadlines-pv:
    image: cursoheadlines-pv
    container_name: cursoheadlines-pv
    networks:
      - cursoheadlines-pv-net
    labels:
      - traefik.enable=true      
      - traefik.http.routers.cursoheadlines.tls.certresolver=letsencrypt-resolver      
      - traefik.http.routers.cursoheadlines.rule=Host(`alexandreafonso.com.br`)
      - traefik.http.routers.cursoheadlines.entrypoints=websecure

networks:
  cursoheadlines-pv-net:
    name: cursoheadlines-pv-net
      